# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specscore < Formula
  desc "SpecScore CLI — lint, validate, and navigate Markdown specifications."
  homepage "https://specscore.md"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/synchestra-io/specscore-cli/releases/download/v1.2.0/specscore_1.2.0_darwin_amd64.tar.gz"
      sha256 "5c6e6ebf740dc3cb25e79b64a504ac0f00b57eacca9d51c6e35fce14c0142784"

      define_method(:install) do
        bin.install "specscore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/synchestra-io/specscore-cli/releases/download/v1.2.0/specscore_1.2.0_darwin_arm64.tar.gz"
      sha256 "1c28c3bf57225e7cc085b55fba7b826e50ca464ca50a969e8128202c1b913731"

      define_method(:install) do
        bin.install "specscore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/synchestra-io/specscore-cli/releases/download/v1.2.0/specscore_1.2.0_linux_amd64.tar.gz"
      sha256 "e53e50ef1bfca877a768f8c07307436cdc66a2b64bb37d86efcecb5ca9919678"
      define_method(:install) do
        bin.install "specscore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/synchestra-io/specscore-cli/releases/download/v1.2.0/specscore_1.2.0_linux_arm64.tar.gz"
      sha256 "283140746a307106a816ee360b445061a6310cde9271c5707ae01d045465a34d"
      define_method(:install) do
        bin.install "specscore"
      end
    end
  end

  test do
    system "#{bin}/specscore", "--version"
  end
end
